version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql.railway.internal
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=sPjyklodDuyAZRMsIRxsdIgOkGBhzYXf